### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TheUltimateCookie** [geziyor/geziyor#49]
I just ran the basic example and got this error

code:
```go
package main

import (
	"fmt"

	"github.com/geziyor/geziyor"
	"github.com/geziyor/geziyor/client"
)

func main() {
	geziyor.NewGeziyor(&geziyor.Options{
		StartRequestsFunc: func(g *geziyor.Geziyor) {
			g.GetRendered("https://httpbin.org/anything", g.Opt.ParseFunc)
		},
		ParseFunc: func(g *geziyor.Geziyor, r *client.Response) {
			fmt.Println(r.HTMLDoc.Find("title").Text())
		},
		//BrowserEndpoint: "ws://localhost:3000",
	}).Start()
}
```

error:
```
Scraping Started
Crawled: (200) <GET https://httpbin.org/anything>
runtime error: invalid memory address or nil pointer dereference goroutine 40 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/geziyor/geziyor.(*Geziyor).recoverMe(0xc00016cdc0)
        C:/Users/Marshall/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20220429000531-738852f9321d/geziyor.go:307 +0x45
panic({0x111dc60, 0x17f7d60})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
main.main.func2(0xc00014a1c8?, 0xc000409d10?)
        C:/Users/Marshall/Desktop/gezi/main.go:16 +0x18
github.com/geziyor/geziyor.(*Geziyor).do(0xc00016cdc0, 0xc0001524b0, 0x12350c8)
        C:/Users/Marshall/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20220429000531-738852f9321d/geziyor.go:262 +0x235
created by github.com/geziyor/geziyor.(*Geziyor).Do
        C:/Users/Marshall/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20220429000531-738852f9321d/geziyor.go:228 +0xd2

Scraping Finished
```

Any advice?

**Comment by musabgultekin** [comment]
Looking rn

**Comment by musabgultekin** [comment]
The url that you're requesting is not an html. Its json document. So HTMLDoc is nil in this case. This is why you're getting that error. Try using an html page. And not json page
