### ISSUE TITLE
Brave browser doesn't work with geziyor

### ISSUE THREAD

**Issue by arjendevos** [geziyor/geziyor#69]
I have brave browser installed and for as far as i know brave browser is build on top of chrome. So it should work right?

It doesn't run without BrowserEndpoint and If i specify the browser endpoint i get this:
```
Scraping Started
interface conversion: interface {} is nil, not string goroutine 54 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/runtime/debug/stack.go:24 +0x68
github.com/geziyor/geziyor.(*Geziyor).recoverMe(0x1400032a000)
	/Users/arjen/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20230315135110-a242b58aaa65/geziyor.go:307 +0x40
panic({0x103573c60, 0x14000320b70})
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/runtime/panic.go:838 +0x204
github.com/chromedp/chromedp.detectURL({0x1033fcc7f, 0x14})
	/Users/arjen/go/pkg/mod/github.com/chromedp/chromedp@v0.8.0/util.go:72 +0x2ac
github.com/chromedp/chromedp.NewRemoteAllocator({0x103640748?, 0x140001b4008?}, {0x1033fcc7f, 0x14})
	/Users/arjen/go/pkg/mod/github.com/chromedp/chromedp@v0.8.0/allocate.go:513 +0x48
github.com/geziyor/geziyor/client.(*Client).doRequestChrome(0x14000312080, 0x14000342000)
	/Users/arjen/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20230315135110-a242b58aaa65/client/client.go:176 +0x70
github.com/geziyor/geziyor/client.(*Client).DoRequest(0x14000312080, 0x14000342000)
	/Users/arjen/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20230315135110-a242b58aaa65/client/client.go:96 +0x30
github.com/geziyor/geziyor.(*Geziyor).do(0x1400032a000, 0x14000342000, 0x1036362b0)
	/Users/arjen/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20230315135110-a242b58aaa65/geziyor.go:246 +0xe0
created by github.com/geziyor/geziyor.(*Geziyor).Do
	/Users/arjen/go/pkg/mod/github.com/geziyor/geziyor@v0.0.0-20230315135110-a242b58aaa65/geziyor.go:228 +0xc8

Scraping Finished
```

**Comment by melroy89** [comment]
Maybe geziyor should update their chromedp dependency first.

But then again it's up to chromedp. And since this is created by Chrome, I fear they won't likely want to support brave. I hope brave can be compatible with chromedp tho. I also really don't want to use chrome!
