### ISSUE TITLE
Test failed (TestPostFormUrlEncoded)

### ISSUE THREAD

**Issue by melroy89** [geziyor/geziyor#75]
When running `go test .`, I expect all tests to succeed.

However, the following test seems to fail due to a robots.txt issue?

```sh
Scraping Started
Forbidden by robots.txt: https://reqbin.com/echo/post/json
Scraping Finished
--- FAIL: TestPostFormUrlEncoded (0.00s)
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 35691 [running]:
testing.tRunner.func1.2({0xb78f60, 0xd70a60})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0xb78f60?, 0xd70a60?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
net/url.Values.Set(...)
	/usr/local/go/src/net/url/url.go:903
github.com/geziyor/geziyor_test.TestPostFormUrlEncoded(0xc0000e16c0?)
	/home/melden/geziyor/geziyor_test.go:250 +0x50
testing.tRunner(0xc0000e16c0, 0xcb8fb8)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x390
FAIL	github.com/geziyor/geziyor	25.706s
FAIL
```

**Comment by melroy89** [comment]
This is simply because `echo` is not allowed to be scrapped: https://reqbin.com/robots.txt

**Comment by melroy89** [comment]
Executing the POST request manually seems to give the correct result with a `<h1>` header text:

![image](https://github.com/user-attachments/assets/9d87772f-5d30-4d4d-9549-1be90d3c7463)


Executing Geziyor test case with `RobotsTxtDisabled: true,` additional option line, gives me:

```sh
Scraping Started
Crawled: (403) <POST https://reqbin.com/echo/post/json>
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.pow-button{background-color:#0051c3;border:.063rem solid #0051c3;border-radius:.313rem;color:#fff;font-size:.875rem;line-height:1.313rem;margin:2rem 0;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff;cursor:pointer}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}.rtl .heading-favicon{margin-left:.5rem;margin-right:0}.rtl #challenge-success-text{background-position:100%;padding-left:0;padding-right:42px}.rtl #challenge-error-text{background-position:100%;padding-left:0;padding-right:34px}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "reqbin.com",cType: 'managed',cNounce: '4331',cRay: '8b1a9bdcaea07805',cHash: 'e8b6d038ab5906b',cUPMDTk: "\/echo\/post\/json?__cf_chl_tk=G5aHG3gDPwW8BjB9P28uGsbi5jEcjhYAZ_FK2DSGFmk-1723404297-0.0.1.1-3817",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '390000',cTplV: 5,cTplB: 'cf',cK: "",fa: "\/echo\/post\/json?__cf_chl_f_tk=G5aHG3gDPwW8BjB9P28uGsbi5jEcjhYAZ_FK2DSGFmk-1723404297-0.0.1.1-3817",md: "l1lej17QZ_oahM1xxNCmYtbmHHAXEm6fk0allqQVAm8-1723404297-1.1.1.1-Pi1dKfSG3iM9LCwQduP298.A5LJV_kDpdxz1.46GedkWPNYxZMZj5rAFc4e3w4rMFajH46fWrHN63ZNTnJ._fKS7MSCPrzD_AzToxUmx54G3tx8ipVMF2KYvXWTXzigH65q9cBknjN3HwlYu0C6zn.zXAJ_JdL..jKaBUgLltzSm.av.TiNtNf0k8S1RuLetIP8PfRG_x0fDhjVILPqmV2bDLo8NX24YnRXENgEO2aQtGRlkvm_GPs9sKzC7gv1vNGAOHcLDUUB3JIKOhHvcVWNMyM6Xuvf37Qt73a.AfsS7ntZcXzMeZ5yE.flXPXiCP7leBu2cVCXjxmbCzO90pHn83CK_HJQh5On08sbu1loLTBpKlkoTllYPkUg1HeT2J_piPJ0cdy7J5O637CvvjmpKtFZ.5cBfdBL6i6TPreIVH6ifcUbNSpdbExtLJJILwVG1UqGYaq.pqZc86Ul4Rr3FBMgNRjoZUI80lY_ErI0S44bR84FnA2p2e2PZ3c9pTCdEevf2E94dxBMQAe6ctAmnOX8A63XK3dhtdmD.4p5_8T.NbidXF8S7iB0PDOauOkITQkLjC8ehPMnDamLxDbii3nHx8cg_26rQOjVPQtBtmEcxGVp3t8W_0Le3nCg_r.I2y5jDQ4NbTRIa6kUJUGUqqGzTowt0V51axtO9ktx9Fz0hgdxz5npKstNrAAWNjD9vdadZdAX6QbUvtngV8CJNtRlnbpZkbdkgRb.HE00ngKDViCT2dSN5aFaLsXT5VIbEdex0HKLYqGek.xzPKFVzilSq2lt6p.2ZKT97x7.HZ4nuvJc6d3RH0LwNttVfwfJC3kT1Qj6p5H.GSPNnxjhHue.OeTpHj7RbyKSN69NvaUBOtTafoSfmKLn9yrExNsDEwj2vwhX.h9ieeUiM_bzIzGIn.SVCUyqPKop36E_FC5H3PCwLrV1ahA_d6sdxt4qZ9PxIx8wlJwlHP0W4n5IRnbwLDhtoiXCNDQZREKWxn4vtZl2.WOcZdVPbTDpnIfL.wYYSbqunSAutwvU13.z3.NRJ8VqP5gvHalNpGN8E5lm9kfsHVN8X9OmlpFbwAiXIGtn_QFuj_DFnoFHSnlPLT1g5AHLqXQKDZZwbnqueuCv2nBr.SRT_pY5uvdJzO08f4L8dmXk8t31ZL8uibN5cx.gEGFjbtZCLrcTTfaIs23cwOsoq8bM60P6FZI7ygUt8aJ3duZoJLHGDFTSDIOGmYY7a7jxRAW9h2mbAJldYikwpbHdwByA5DZzokvmro9s8Xk43BNgEL5aYpQGG82LXMsWpt4NAcLQw.EuSOxGPGj2bqghS4Ntwpz3KrX8ZKG6l713N9FsbHXLIMRtpPbEUr4OV_.6mTu4O6dIQAvwIfxKFgqjreJ1BS6v66JV9l6achhKxn5WdUHZYtstywJfFqnYywsUfZaEAReIB8IeBvOPFX1YhTZFJOKxIMiSDs2rYRob5e.VBReJY587CuTVd9okHMkBmDtfgPB3OSU4",mdrd: "O63AmLXqFvnXO6bAMJR9Gq4GRL3IpLRza6mJMQGEgRw-1723404297-1.1.1.1-RWHC3w9ePkfO2tHqvhALkcR1BbIgCuQ3N2nKF8dSInxdW9mU0rJXZ3ySkt5svcFZdrCz2bROlxU4zxs9YVL16Di7Q3zJvCjw8aGTmV4vUND.eemBzvAfBOlsO4HFu3wFPLPU4AmwdU.n6sKN96LXvjF7uI67m7eE5n.B_UXVtuO3J83YXbzP0Dpzs1k.yotoNImxCHXS5qMgfJTFkt2RSgztISm1zftrG1QV56_5dv0aLay4SjfqNCEgByUg0IlLT1PV7T5XcHgYOnuxWuiD4InItxgMMINb7hAC7e74jGLYA2IB1j1KfG6xfTq9sWQ_Pti0h1ia13RiiJhtibuuRXaxcCmaMLqjEghuB80nPyzLWUCRPQZd692dF3DpkGyNYiLLTrVk6Ip4mYkRb3FjkSuWcmx9VWhDdnFRbCX5OpnjKP5e1y_CEKeB48JR0yXasKZWkKHMQ5geBgfxTx9k3INO6zDyjlsHalBdmdMmvD2fEhx3YQsBl7jngyoKCmyfBG7ysqiozX5JX1PcFAXccO8P4bR3VrsWVBs5eaZoQsmr32irQlUR_QZowd4vorth8tGvy74NUqMSpPeoQ17vzkX1HWODGLH2rlBVzmTim5UDPEkZdyhpJ0IKZVsqX3QMsq1PUQMBwBR23JlKsyLqtvLezGE15b_ywEXPIEChbtpjIwSNaR.VnZGYkFysr4OOArwjpeotwYkFhSPkkZxpdT8GVDuFVg7n6Zz0aUc2nk3dAG0FUleMzMVz50Pi51pc0tlTs1NgJ0aJrRNatzFXL6C0HIJNXPXYKILyWxDnLrVviv_wilIEfxEelwyHoaAhuJIKlbz3zhWOPtVtjDhVXX6.urxmaYshQWyP.xsGyho5aPr0L2SjBHlzGRpyWlfQlwAGIbqnMUMXIcACwDl2tYLD5gT_zHnDOSBwpTDj5F89kH7XtMoW1ksqelEuHEH1M3bEBvQHhBAprecONgakWbrsmcAuuv9nvmQsQQEcuhCLeVZZbvOqqdkDRnWunBlIE2nEV7A7tk74lb51AXosSe3_5dnTsGmbEnriEclQLcrRPguUxnNBxkYgWobmrq9AL.P8oRON9dcOX5YuA.k.loq9kBG.MKHyIO5sznJHJ4xMkwErzdAwxL6oS.EV1D_lfH8vMKiKaygFJrrul9s7b64ZoMjEd9Y4xljEXAZ_uPrChCpO_qqmX_0RrqUVq238kFhk9CfxwNu78FCHtHicD2Xvah4B85dJXKFhIdi9wLqyarD6qohcvejMGzHjfsAy..FPKwWJnf_TfE_X5oC1nCGBZFR25LalKI740luZzIvgJDSUtG27X_GiKuG5inZ_V99rYTgM_trZzyxdAkBNVJzwtECMoGRjQt4P1bUh6Ixhrxqm_YZhYrWDhd.6.V8hyUKrCBqnnGvVaw..a4DHbuzSPerkmgWvV8XdchE0WYqN3NifQZ5cO9MbCSTnJHuHFFYDaO1wPgyrdpqdaj5qfIkwuUYwHMGEPnFWIpThwmclNeyCuyhEL5Lk.R_t.8ingYfglsp27eolIgyPTTIo8D7P1ZGLr8ezv4vygI2Gk6e_8Y4aG8oPpouP8wLLyMxqOMU7KdmY8PCmP7CfrmVpqibgHZaZFdP1wZHr3BbsJ5e97AgC0IHomdssIKG1yMVcd4qpU34xA.UrLkB9Sf4d.vqt9tVQAXZmk_JPanU6dIDHfipLZyhINWtGx5eRKOMPmh7mjjTzJ3AU1y_Mtk66CizgfJaOHGMhTuuZTDBeXUkv6q8IgSLiZJHHlQLh40WPWH78tHWNSWK..3YARFcuBLhQCvwVBDYfwvP_cqki1PplFucIUszBTsYdGa1QQV32CbmCquCx6CVUo6s2lFxk9kubFdcuZd91y89auCvzaiDS3_p_i.ViPpjHBBfDik7hkye9lwJR.STlCW9K2EAMGYKHor_HeYji8SxFxScNihiD.f.uemxVwW_Tmd4fo3KOf_iXLocN2..lJWYoRMrCSjyk1DnSVTcNGo6xC_27B.zTGKc7zHgUo_7BCx7iHwjL3Sgllfa9ZIop0q8O2J6kMz7TrpuotjIFErqQvZNI3WYDfmu6ERxbDBhx11fsbkvHIpwScvAYbo1AowmV71Mw1VXM9bNdOTRH4hkZwbYef3HzGu.VCE7CrSIMtAkjAMEN",cRq: {ru: 'aHR0cHM6Ly9yZXFiaW4uY29tL2VjaG8vcG9zdC9qc29u',ra: 'R2V6aXlvciAxLjA=',d: 'eMTBHPkeFihTxNxVbF8dvUpDxeg1nTB9C4BjfvybA+R+lBZxmVOpErgynGTWkA+zTtKf2f1HB/C0/qSrVcw7hkkLigHKc0QApjZQO8sq7+95zwp/Z8gzxLotbxY7uWgIjNgwGYYBqBJiU1h5AzKetDRUZLpktoIIMOQgxjmdBtFdth1LILb044yh99KnCVPKCNqwHLgqPk3M8mQIxLR6n5IoqYEyFoInllky+BnG6Eh0BIan6Ekff0KE492cE35KbKDI+KOxB3fns65aVhZ15H6Wm0NszVLAk4P4qpmDLZjzX9vYqn6bpNGW8d6mtXvjuOoAAyJFfUjcSsM7UJViSWLQYdkbXTAfAG+SoIErbnGKlZK0Upb39ZN7zbIZQfhHIfV1rbZ8I+2JjPSnjcuQA6WQ6zrYFSKGnPQC6gJyEtC92+MacRehfnIB6dE3YRPltcYJMWtXhe7TlCELf1RIrBG+C8RLDUnYu+rAmDCYN4KiWqD5AojLctkG7pQE9PolLgxcDZng73nSmPmq9cYL52PvTtLjz4c/nHuTMgB99P0FTtgjI146tmCFhd5/USImvj7o/VOJYAXIpXqPUfAHGA==',t: 'MTcyMzQwNDI5Ny4wMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: 'VS7yZZr/tr+p6td8ODxRjfAr0mlgThMwfbHe2OACBP8=',i1: '/ZWqi0c0yaFexI6zFQgzmQ==',i2: 'WmZs0MD8aJmYQc1vUSqM5Q==',zh: 'LCW3AZH/FGYMtoptFGg2LyVk23ScKwRlpKwnq4Z30Ks=',uh: 'TJRcWPrp5c+c52+pcKr/C8coHIjUEPoQGrJzCegQ3MM=',hh: 'vrpRu8Ley44OIG8+ikOYvBHgHkkGD06acbUIcsoF9q0=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8b1a9bdcaea07805';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/echo\/post\/json?__cf_chl_rt_tk=G5aHG3gDPwW8BjB9P28uGsbi5jEcjhYAZ_FK2DSGFmk-1723404297-0.0.1.1-3817" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
Scraping Finished
--- FAIL: TestPostFormUrlEncoded (0.00s)
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 35674 [running]:
testing.tRunner.func1.2({0xb78f60, 0xd70a60})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0xb78f60?, 0xd70a60?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
net/url.Values.Set(...)
	/usr/local/go/src/net/url/url.go:903
github.com/geziyor/geziyor_test.TestPostFormUrlEncoded(0xc000c1c340?)
	/home/melden/geziyor/geziyor_test.go:251 +0x50
testing.tRunner(0xc000c1c340, 0xcb8fb8)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x390
FAIL	github.com/geziyor/geziyor	20.245s
FAIL
```
